### ISSUE TITLE
GPS broken

### ISSUE THREAD

**Issue by not-availabIe** [Toomoch/android_device_lge_bullhead#1]
GPS positioning is broken.
The phone can only use positioning with WiFi, mobile signal etc but not actual GPS

**Comment by Toomoch** [comment]
This build should've fixed it: https://androidfilehost.com/?fid=8889791610682942268
Can you confirm?

**Comment by not-availabIe** [comment]
Is there a non-blod build pls? Thanks

**Comment by Toomoch** [comment]
> Is there a non-blod build pls? Thanks

No, I didn't do a normal build as it just was for a test, but afaik you can migrate from a normal to blod and the other way around.

**Comment by not-availabIe** [comment]
alright then, just flashed and I think GPS is working now.

**Comment by dalz** [comment]
Sorry to bother you @Toomoch, but it still isn't working for me. I updated (that is, wiped and reinstalled) from the july build to  the 2021-01-22 non-blod one, and I can't get the GPS to work. Any idea why?
